export const IMAGE_SLOTS = {
  'workshop-overview': { label: 'Workshop Overview', page: 'Workshop', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/workshop/workshop overview.jpeg' },
  'workshop-training': { label: 'Workshop Training', page: 'Workshop', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/workshop/workshop-training.jpeg' },
  'street-play': { label: 'Nukkad Natak', page: 'Workshop', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/workshop/street-play.jpeg' },
  'residential': { label: 'Non-Residential card image', page: 'Workshop', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/workshop/residential.jpeg' },
  'non-residential': { label: 'Residential card image', page: 'Workshop', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/workshop/non-residential.jpeg' },

  'field-perform': { label: 'Field Performance', page: 'Awareness Program', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/awareness/field-perform.jpeg' },
  'community-engagement': { label: 'Community Engagement', page: 'Awareness Program', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/awareness/community engagement.jpeg' },
  'child-rights': { label: 'Child Rights Skit', page: 'Awareness Program', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/awareness/child-rights.jpeg' },
  'village-play': { label: 'Street Play', page: 'Awareness Program', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/awareness/village-play.jpeg' },
  'rehearsal': { label: 'Rehearsal Session', page: 'Awareness Program', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/awareness/rehearsal.jpeg' },
  'slum-intervention': { label: 'Slum Intervention', page: 'Awareness Program', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/awareness/slum intervention.jpeg' },

  'dance-1': { label: 'Dance Training 1', page: 'Other Activities', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/other-activities/Dance 1.jpg.jpeg' },
  'dance-2': { label: 'Dance Drama', page: 'Other Activities', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/other-activities/Dance2.jpeg' },
  'art-workshop-f3': { label: 'Stagecraft Workshop', page: 'Other Activities', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/other-activities/Art Workshop F3.jpeg' },
  'art-workshop-f2': { label: 'Stage Design Workshop', page: 'Other Activities', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/other-activities/Art workshop F2.jpeg' },
  'art-workshop-f1': { label: 'Set Craft Session', page: 'Other Activities', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/other-activities/Art workshop F1.jpeg' },

  'festival-1': { label: 'Muktamancha', page: 'Festivals', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/festivals/Festival 1.jpeg' },
  'festival-5': { label: 'Antaranga', page: 'Festivals', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/festivals/Festival 5.jpeg' },
  'festival-3': { label: 'Gallery Moment 1', page: 'Festivals', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/festivals/Festival 3.jpeg' },
  'festival-4': { label: 'Gallery Moment 2', page: 'Festivals', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/festivals/festival 4.jpeg' },
  'festival-2': { label: 'Gallery Moment 3', page: 'Festivals', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/festivals/Festival 2.jpeg' },
  'festival-6': { label: 'Gallery Moment 4', page: 'Festivals', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/festivals/Festival6.jpeg' },

  'paper-review-1': { label: 'Paper Review Inauguration', page: 'Paper Reviews', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/paper-review/paper review inoguration 1.jpeg' },
  'paper-review-2': { label: 'Paper Review Kalobag', page: 'Paper Reviews', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/paper-review/6 paper review kalobag 16.jpeg' },
  'paper-review-3': { label: 'Paper Review Favourite Bou (1)', page: 'Paper Reviews', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/paper-review/5 paper review favourite bou 7.jpeg' },
  'paper-review-4': { label: 'Paper Review Sanrashi', page: 'Paper Reviews', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/paper-review/2 paper review sharashi 3_Fotor.jpeg' },
  'paper-review-5': { label: 'Paper Review Char Akshwar (1)', page: 'Paper Reviews', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/paper-review/7 paper review char akhswar 14.jpeg' },
  'paper-review-6': { label: 'Paper Review Favourite Bou (2)', page: 'Paper Reviews', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/paper-review/4 paper review favourite bou 8.jpeg' },
  'paper-review-7': { label: 'Paper Review Pharrheziasth', page: 'Paper Reviews', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/paper-review/paper review faregiaste 15_Fotor.jpeg' },
  'paper-review-8': { label: 'Paper Review Char Akshwar (2)', page: 'Paper Reviews', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/paper-review/8 paper review char akhsawr 13.jpeg' },

  'gallery-1': { label: 'Gallery 1', page: 'Gallery', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/gallery/Gallery 1.jpeg' },
  'gallery-2': { label: 'Gallery 2', page: 'Gallery', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/gallery/Gallery 2.jpeg' },
  'gallery-3': { label: 'Gallery 3', page: 'Gallery', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/gallery/Gallery 3.jpeg' },
  'gallery-4': { label: 'Gallery 4', page: 'Gallery', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/gallery/Gallery 4.jpeg' },
  'gallery-5': { label: 'Gallery 5', page: 'Gallery', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/gallery/Gallery5.jpeg' },
  'gallery-6': { label: 'Gallery 6', page: 'Gallery', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/gallery/Gallery 6.jpeg' },

  'production-1': { label: 'Shiri Bhenge Surjo', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/Siri Bhenge Surja.jpg.jpeg' },
  'production-2': { label: 'Otit Bartaman', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/Otit Bartaman F.jpg.jpeg' },
  'production-3': { label: 'Karna Kunti Sangvad', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/3 karna kunti sangbad.jpeg' },
  'production-4': { label: 'Sanrashi', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/Sanrashi.jpg.jpeg' },
  'production-5': { label: 'Bhat', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/Bhat Poster.jpeg' },
  'production-6': { label: 'Kalobag', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/Kalobag.jpeg' },
  'production-7': { label: 'Favourite Bou', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/Favorite-Bou.jpeg' },
  'production-8': { label: 'Pharrheziasth', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/Pharrheziasth.jpeg' },
  'production-9': { label: 'Bite', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/bite.jpeg' },
  'production-10': { label: 'Bhagaban Dot Dot', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/10 bhagaban Dot Dot.jpeg' },
  'production-11': { label: 'Kidnap Kando', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/Kidnap Kando.jpeg' },
  'production-12': { label: '2973190', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/12 2973190.jpeg' },
  'production-13': { label: 'Char Akswar', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/Char Akswar.jpeg' },
  'production-14': { label: 'Kunda Phooler Mala', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/Kunda fuler mala .jpeg' },
  'production-15': { label: 'Sharbanggo Sundar', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/SharbanggoSundar2.jpeg' },
  'production-16': { label: 'Jampuri Jamjamat', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/Jampuri Jamjamat.jpeg' },
  'production-17': { label: 'Le Jhilli', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/Le Jhilli.jpeg' },
  'production-18': { label: 'Durneety Darpan', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/Durniti Darpan F 17.jpg.jpeg' },
  'production-19': { label: 'Mahabidya Adhikontu', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/Mahabidha.jpeg' },
  'production-20': { label: 'Apekhsha', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/Apekhha.jpeg' },
  'production-21': { label: 'E Parobashe', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/E parobashe.jpeg' },
  'production-22': { label: 'Mon Paboner Nao', page: 'Productions', fallback: 'https://uivhxj5th4bjhbpl.public.blob.vercel-storage.com/productions/poster mon paboner nao.jpeg' },
} as const

export type SlotKey = keyof typeof IMAGE_SLOTS